### ISSUE TITLE
No screenshots are created

### ISSUE THREAD

**Issue by mstalfoort** [fouber/pmui#1]
I followed all the steps from your readme yet I don't see any screenshot being generated.
Can you help me out please?

**Comment by fouber** [comment]
## 1. First of all, install pmui as global cli tool:

``` bash
npm install -g pmui
```

## 2. Then, make a dir:

``` bash
mkdir page-monitor
```

## 3. And get into it:

``` bash
cd page-monitor
```

## 4. Launch ui server at this dir

``` bash
pmui server start
```

## 5. At this time, you can browse an ui view at port `8994` like this:

![image](https://cloud.githubusercontent.com/assets/536297/4168520/41219f66-351d-11e4-85af-0fc1e8d71194.png)

## 6. Still in this dir, install `page-monitor` package:

``` bash
npm install page-monitor
```

> NOTICE, without `-g` option.

## 7. Still in this dir, create a monitor script:

``` bash
vim www.google.com.js
```

with the content of this:

``` javascript
var Monitor = require('page-monitor');
var url = 'http://www.google.com/';
var opt = {/*...*/};
var monitor = new Monitor(url, opt);
monitor.on('debug', function (data) {
    console.log('[DEBUG]' + data);
});
monitor.on('error', function (data) {
    console.error('[ERROR] ' + data);
});
var timeout = 60 * 1000; // 1 minute a capture
(function(){
    var callee = arguments.callee;
    monitor.capture(function (code) {
        console.log('[DONE]');
        setTimeout(callee, timeout);   // interval
    });
})();
```

## 8. Try to run it with nodejs first

``` bash
node www.google.com.js
```

> NOTICE, it will console out some information, if there is any error, report it here.

## 9. If there is no error, run it with `pmui run` command:

``` bash
pmui run www.google.com.js
```

**Comment by fouber** [comment]
@mstalfoort 

## 10. Reload page of ui that we launch at `step 5`, you may see this:

![image](https://cloud.githubusercontent.com/assets/536297/4168688/7a3199da-351f-11e4-83fa-53916c01bdc5.png)

**Comment by fouber** [comment]
@mstalfoort 

I'm sorry, the screenshot at step 10 is not google's, beause, in my country, we can't visit google for some political reasons. But it doesn't matter, I'm sure it's the same as google.com

**Comment by fouber** [comment]
@mstalfoort 

In the work dir, if you captured successfully, it will create some files like this:

``` text
page-monitor
  ├─ www.baidu.com
  │   └─ Lw==
  │       ├─ 1409936892182
  │       └─ latest.log
  └─ www.baidu.com.js
```

**Comment by mstalfoort** [comment]
after running the node command i get the following error

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

**Comment by mstalfoort** [comment]
on ubuntu 14.04:
node -v
v0.10.21

npm -v
1.3.11

**Comment by fouber** [comment]
@mstalfoort 

Did you installed [phantomjs](http://phantomjs.org/) in your system?

**Comment by fouber** [comment]
@mstalfoort 

Maybe you haven't installed [phantomjs](http://phantomjs.org/) yet.

Install it, and make it global, if you can run `phantomjs` command in terminal directly like this:

``` bash
> phantomjs -v
1.9.7
```

the problem should be fixed.

**Comment by mstalfoort** [comment]
i'm so sorry, my phantomjs wasn't really working with me anymore so had to reinstall it
and now it's all working.

thanks so much for your help and fast replies :+1:

**Comment by mstalfoort** [comment]
Am I missing software for phantom to create the diff files because I don't see them being  generated

**Comment by fouber** [comment]
@mstalfoort 

It depends only on phantomjs, you don't need to install any other software. Generally, it won't generate another screenshot until there are `VISIBLE` changes of webpage, so, if you are monitoring google.com, very few change you will get, so you can try to monitor some news news websites, there will be some many changes in one day.

Here is a video website in China, it modifies almost every minute. (a very very long page!)

https://cloud.githubusercontent.com/assets/536297/4185084/f7fb9304-3752-11e4-9801-66fa09dc9daa.png

**Comment by mstalfoort** [comment]
sounds perfect and legit, 
only thing I'm experiencing is that I have 3 screenshots now and I see them in the page-monitor web application and by clickiing on the second and third thumbs I see a 404 in my console which requests for a diff image but it's not generated
the site I'm testing with is : http://www.enrise.com

**Comment by mstalfoort** [comment]
![selection_218](https://cloud.githubusercontent.com/assets/496796/4185280/50f9a386-3755-11e4-801c-b1e3a2cfa495.png)

**Comment by fouber** [comment]
@mstalfoort 

get back into the work dir, could you list the files of it?

mine are:

``` bash
page-monitor
  ├─ www.enrise.com
  │   └─ Lw==
  │       ├─ 1409936892182
  │       ├─ 1409936893182
  │       ├─ ...
  │       ├─ 1409936897182
  │       ├─ diff
  │       │   ├─ 1409936892182-1409936893182.png
  │       │   ├─ 1409936893182-1410108202384.png
  │       │   ├─ ...
  │       │   ├─ 1410108202384-1409936897182.png
  │       └─ latest.log
  └─ www.enrise.com.js
```

there is a dir called `diff`, is there any picture in there?

**Comment by fouber** [comment]
@mstalfoort 

Er, i saw it, maybe it's a bug... there is no diff but it still generate a screenshot, i will fix it as soon as possible, try some other webpages.

**Comment by mstalfoort** [comment]
my dir looks like the following

```
├── node_modules
│   └── page-monitor
│       ├── index.js
│       ├── package.json
│       ├── phantomjs
│       │   ├── diff.js
│       │   ├── highlight.html
│       │   ├── highlight.js
│       │   ├── index.js
│       │   └── walk.js
│       ├── README.md
│       └── util.js
├── www.enrise.com
│   └── Lw==
│       ├── 1410176862158
│       │   ├── info.json
│       │   ├── screenshot.png
│       │   └── tree.json
│       ├── 1410178965014
│       │   ├── info.json
│       │   ├── screenshot.png
│       │   └── tree.json
│       ├── 1410179027172
│       │   ├── info.json
│       │   ├── screenshot.png
│       │   └── tree.json
│       └── latest.log
├── www.enrise.com.js
```

**Comment by fouber** [comment]
@mstalfoort 

i see, this is a bug and i already know how it happens, i will fix it as soon as possible.

`enrise.com` doesn't have change for a long time, did you set the `viewportSize` option to make a diff and generate a screenshot? in this case, some elements rect have change, but [page-monitor](https://github.com/fouber/page-monitor) won't accept those changes, so here's the bug: generate a screenshot but no diff. I will fix it later, thank you for your report.

Try some other websites like youtube.com, it changes very minute, you will see the diff.

Please excuse my poor English.

**Comment by mstalfoort** [comment]
no worries,
I'm very happy with your support and look forward to the updated version

**Comment by fouber** [comment]
@mstalfoort 

I have fixed the bug just now, thank you for your reporting!

**Comment by fouber** [comment]
@mstalfoort 

upgrade page-monitor package:

``` bash
cd page-monitor
npm update page-monitor
```

the latest version is `0.3.3`

**Comment by mstalfoort** [comment]
successfully updated and it's fixed indeed

thanks for all your efforts
